---
canvas: https://canvas.mit.edu/courses/24163
lectures:
  - day: Tuesday
    time: "11:00 AM--12:30 PM"
    room: "4-163"
  - day: Thursday
    time: "11:00 AM--12:30 PM"
    room: "4-163"
recitations:
  - day: Tuesday
    time: "3:30--4:30 PM"
    room: "4-163"
  - day: Tuesday
    time: "4:30--5:30 PM"
    room: "4-163"
  - day: Wednesday
    time: "3:00--4:00 PM"
    room: "4-163"
  - day: Wednesday
    time: "4:00--5:00 PM"
    room: "4-163"
  - day: Thursday
    time: "10:00--11:00 AM"
    room: "4-163"
staff:
  instructors:
  - name: Eric Robsky Huntley, PhD
    title: Lecturer in Urban Science and Planning
    pronouns: they/them
    email: ehuntley@mit.edu
    office: 9-545
    office_hours: 
    - day: Thursday
      time: "5:00--7:00 PM"
      room: "9-554 (CRON Lab)"
  phd_instructors:
  - name: Mary Louise Chatters Taylor
    title: PhD Student
    pronouns: she/her
    email: marytayl@mit.edu
    office_hours: 
    - day: Wednesday
      time: "11:00 AM--12:00 PM"
      room: "Room TBD"
    - day: Wednesday
      time: "1:00--2:00 PM"
      room: "Room TBD"
  - name: Chenab Navalkha
    title: PhD Student
    pronouns: she/her
    email: chenab@mit.edu
    office_hours: 
    - day: Tuesday
      time: "2:00--3:00 PM"
      room: "Room TBD"
    - day: Thursday
      time: "1:00--2:00 PM"
      room: "Room TBD"
  - name: Nishan Zewge-Abubaker
    title: PhD Student
    pronouns: she/her
    email: nishanz@mit.edu
    office_hours: 
    - day: Tuesday
      time: "10:00--11:00 AM"
      room: "Room TBD"
zotuser: 2395373
first_class: "2024-02-06"
miss_days: ["2024-02-20"]
textbooks: "SEU92Q74"
