---
title: "Discrimination Against Voucher-Holders"
thanks: "This exercise is written by Justin Steil, with substantial revisions by Eric Robsky Huntley."
subtitle: "Exercise 1"
output: 
  pdf_document: 
    template: '../templates/syllabus.latex'
---

## Introduction: Housing Vouchers

To help low-and moderate-income households, individuals with disabilities, and other vulnerable groups secure stable housing, federal, state, and local governments have created a number of housing voucher or subsidy programs. These housing voucher programs differ in their eligibility requirements and the details of their operation, but have several shared characteristics.

1. First, the programs are designed so that households can select in the private rental market their own homes that meet the program’s quality standards.
2. Second, the subsidies in the programs are generally based on a local “payment standard” or “fair market rent” that reflects the cost to lease a unit in the local housing market.^[See, e.g., 24 C.F.R. § 982.1(a)(3) (“Subsidy in the HCV program is based on a local “payment standard” that reflects the cost to lease a unit in the local housing market.”). Fair market rents are gross rent estimates including both rent paid by the tenant and the cost of tenant-paid utilities, except telephones. HUD sets FMRs annually for each metropolitan or non-metropolitan statistical area, generally either at the 40th percentile rent or, in some high-cost areas, at the 50th percentile rent, paid by movers within the previous 18 months.]
3. Third, some programs require households to pay some portion of their income (usually 30%) in rent, while others will pay up to the whole value of the rent.
4. Fourth, the agency administering the voucher program assesses participants’ household income to determine the participant’s eligibility and share of the rent, if any, and the agency then enters into a contract with the landlord to make guaranteed rental subsidy payments directly to the landlord for all of the rent or for the remaining portion after a tenant’s payment.^[See, e.g., 24 C.F.R. § 982.1(b)(2) (“To receive tenant-based assistance, the family selects a suitable unit. After approving the tenancy, the PHA enters into a contract to make rental subsidy payments to the owner to subsidize occupancy by the family.”)] If the household has no income, the program usually pays the full rental amount up to the local payment standard or the remaining rent after a nominal contribution from the tenant.^[See, e.g., 24 C.F.R. § 5.630 (stating that “the PHA may establish a minimum rent of up to $50” and “must grant an exemption from payment of minimum rent if the family is unable to pay the minimum rent because of financial hardship”).]

These general policies mean that voucher payments to landlords are contractually guaranteed by the agency.  The policies further mean that the voucher administrator ensures that a tenant payment is generally limited to 30 percent of the household’s income (adjusted for dependents, disabled family members, childcare expenses, etc.) or less.^[See, e.g., 24 C.F.R. § 982.1(b)(3) (“If the rent is less than the payment standard, the family generally pays 30 percent of adjusted monthly income for rent. If the rent is more than the payment standard, the family pays a larger share of the rent.”); 24 C.F.R. § 982.508 (“At the time the PHA approves a tenancy for initial occupancy of a dwelling unit by a family with tenant-based assistance under the program, and where the gross rent of the unit exceeds the applicable payment standard for the family, the family share must not exceed 40 percent of the family's adjusted monthly income.”)]

From a policy perspective, housing subsidies are generally understood to serve at least two crucial goals:

1. helping households with low-incomes afford housing and thereby reducing residential instability and homelessness, while also leaving households with enough residual income to meet their basic needs; and
2. helping low-income households have more choices about where they live, increasing the opportunity to access, if they choose, neighborhoods with lower-poverty rates and more place-based resources.

## Question 1: Landlord Policy A

A landlord applies a test to assess the income eligibility of prospective tenants.

1. Tenants must have a gross annual income greater than or equal to 40 times the monthly rent.

---

Said algebraically, this is...

$40R < 12I$

where...

+ $I$ is is the tenant's monthly income and 
+ $R$ is the monthly rent.

---

2. For applicants with vouchers, the landlord adds the monthly value of the voucher, multiplied by 12, to the tenant’s gross annual income. Assume that the voucher program requires that tenants pay 30% of their income in rent.

---

Said algebraically, this is...

$40R >= 12(I + V)$

where...

+ $I$ is is the tenant's monthly income,
+ $V$ is the monthly value of the voucher, and 
+ $R$ is the monthly rent.

Furthermore, we can say that the value of the voucher is equal to the rent minus the portion paid by the tenant, which is 30% of their income. Therefore, we know that...

$V = R - 0.3I$

where...

+ $I$ is is the tenant's monthly income,
+ $V$ is the value of the voucher, and 
+ $R$ is the monthly rent.

Finally, we know that for a voucher to have value, the rent must be greater than 30% of the tenant's monthly income. So...

$R > 0.3I$

where...

+ $I$ is is the tenant's monthly income and
+ $R$ is the monthly rent.

---

Does this policy treat applicants with vouchers fairly? If so, why? If not, why not? Provide an algebraic response and flesh it out briefly with a one-paragraph summary of your findings. Hint: You know how much a tenant must make for a voucher to have value (solve $R > 0.3I$ for I), and you know how much a tenant would have to make to qualify, assuming they have a voucher (substitute $V = R - 0.3I$ for $V$ in $40R >= 12(I + V)$ and solve for income). What does this say about the tenant's ability to receive a voucher that has value, assuming they qualify based on their income?

## Question 2: Landlord Policy B

The landlord changes the test they apply. 

1. Tenants must have a rent to net income ratio no greater than 40 percent (i.e. monthly rent must be less than or equal to 40% of their net income). Net income is calculated by subtracting taxes and debt service from gross income---this landlord estimates net income by multiplying gross income by 0.7 to arrive at net income.

---

Said algebraically, this is...

$\frac{R}{0.7I} < 0.4$

where...

+ $I$ is is the tenant's monthly income and 
+ $R$ is the monthly rent.

---


2. Tenants with a voucher that pays part of their rent must demonstrate that they have a rent to net income ratio for the portion of the monthly rent that they are paying that is no greater than 40 percent, as for no-subsidy applicants.

Does this policy treat applicants with vouchers fairly? If so, why? If not, why not? Provide an algebraic response and flesh it out briefly with a one-paragraph summary of your findings. Hint: You know what portion of a tenant's income must be paid! Substitute that for $R$ in the equation presented under (1), above and evaluate whether it is less than 0.4 (40%).

## Question 3: Calculating Subsidy for Multiple Units

Finally, let's build an `R` dataframe using some real numbers. The fair market rent in Boston in 2024 is \$2,377 for a one-bedroom. Let's assume a tenant has a voucher that requires they pay 30% of their income in rent. This tenant has an annual income of \$45,000. They've found three one-bedroom apartments, and we assume here that they have not been screened out by landlord criteria. These apartments monthly asking rents are:

Address | rent
---|---
250 Suffolk St | \$1,200
378 Appleton Ave | \$1,900
58 Cabot Dr | \$2,000

First, use `R` to calculate the tenant's monthly income and store it in an object. Then, calculate the expected rent payment, storing it as an `R` object. Finally, create an `R` dataframe that has names taken from the above addresses, and two columns: the price and the monthly voucher subsidy (the rent minus the amount the tenant is expected to pay, which is the same in all cases. You can calculate this using either the `df$subsidy = ` or the `mutate()` function from `dplyr` (though try the latter)!